[env:d1_mini]
platform = espressif8266
board = d1_mini        ; change to nodemcuv2 if using a NodeMCU board
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    knolleary/PubSubClient @ ^2.8

build_flags =
    -D MQTT_MAX_PACKET_SIZE=512
